header:
    title: GenOptics project
    # text: It's Nice To Meet You
    button: Overview
    buttonlink: "#services"

services:
    title: "Overview"
    text: "One of the biggest challenges in Life Sciences is the high complexity and volume of the involved bio-data, as well as the lack of appropriate analysis tools that can be employed for the extraction of new knowledge.
    In the field of bioinformatics, there is an increasing trend towards the development of user-friendly tools for the analysis and interpretation of large-scale bio-data, with a variety of specialized tools and management approaches available in recent literature. 
    <br><br><p><b>Goal of GenOptics is to implement a new platform for integrating, analyzing and visualizing multi-omics and other clinicobiogical data, by extending the functionality of established bioinformatic analysis tools through an interactive visual dashboard</b></p>"
    section: services
    list:
      - title: "Objective 1"
        desc: "Integrate computational data analysis processes with a flexible visualization system as a single process through a visual analytics dashboard. GenOptics' ultimate goal is to conceal from the users the technical complexity generated from the interconnection and integration of heterogeneous and multi-omics biodata as well as the corresponding analysis tools and visualization techniques"
        icon: fas fa-network-wired # https://unsplash.com/photos/zF_pTLx_Dkg #find more at https://fontawesome.com/icons
      - title: "Objective 2"
        desc: "A better exploitation of the accumulated volume of multi-omics data allowing the identification of new biomarkers and new therapeutic targets through targeted clinicobiological studies. The GenOptics platform will be evaluated and validated through four pilot cases: (i) ***chronic lymphocytic leukemia (CLL)***, (ii) ***hepatocellular carcinoma***, (iii) ***colorectal cancer***, and (iv) ***cystic fibrosis***"
        icon: fas fa-search # https://unsplash.com/photos/zF_pTLx_Dkg       

# portfolio:
#     title: "Portfolio"
#     text: "Lorem ipsum dolor sit amet consectetur."
#     section: portfolio
    

# timeline:
#     title: "About" 
#     text: "Lorem ipsum timeline"
#     section: timeline
#     events:
#       - title: "Our Humble Beginnings"
#         year: "2009-2011"
#         desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
#         image: assets/img/timeline/1.jpg
#         alt: 
#         align: left
#       - title: "An Agency is Born"
#         year: "March 2011"
#         desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
#         image: assets/img/timeline/2.jpg
#         alt: 
#         align: right
#       - title: "Jekyll Theme is created"
#         year: "2019"
#         desc: "Ravi Riley converted Agency, a Bootstrap-based theme, into a Jekyll theme. The Jekyll theme can be installed as a Ruby gem, or remotely. For more information, visit the documentation."
#         image: assets/img/timeline/3.jpg
#         alt: image alt text
#         #align: #default is left       
#       - title: "Title"
#         year: "2009-2011"
#         desc: "Your description here, **Markdown** is fully supported."
#         image: assets/img/timeline/4.jpg
#         alt: 
#         align: right
#     end: "Be Part <br> of Our <br> Story!"

# about:
#     title: "About Us"
#     text: "our story"
#     section: about

# clients:
#     section: clients
#     max-height: 100px
#     horizontal-scrolling: "" #"yes/no"
#     list:
#       - title: "envato"
#         url: https://github.com/raviriley/agency-jekyll-theme
#         logo: assets/img/clients/envato.jpg
#       - title: "designmodo"
#         url: https://github.com/raviriley/agency-jekyll-theme
#         logo: assets/img/clients/designmodo.jpg
#       - title: "themeforest"
#         url: https://github.com/raviriley/agency-jekyll-theme
#         logo: assets/img/clients/themeforest.jpg
#       - title: "Creative Market"
#         url: https://github.com/raviriley/agency-jekyll-theme
#         logo: assets/img/clients/creative-market.jpg
    
team:
    title: "PARTNERS"
    text: "Here is the members of our consortium"
    subtext: Project. **GenOptics**
    section: team
    people:
      - name: "INAB-CERTH"
        role: "Partner 1"
        image: assets/img/team/certh.jpg
        social:
          - url: https://www.inab.certh.gr/
            url_description: INAB CERTH website
            icon: fas fa-link
          # - url: https://facebook.com
          #   icon: fab fa-facebook-f
          # - url: https://linkedin.com
          #   icon: fab fa-linkedin-in
      - name: "IMBB-FORTH"
        role: "Partner 2"
        image: assets/img/team/forth.png
        social:
          - url: https://www.imbb.forth.gr/en/
            url_description: IMBB FORTH website
            icon: fas fa-link
          # - url: https://facebook.com
          #   icon: fab fa-facebook-f
          # - url: https://linkedin.com
          #   icon: fab fa-linkedin-in
      - name: "Faculty of Medicine- University of Ioannina"
        role: "Partner 3"
        image: assets/img/team/University-of-Ioannina.jpg
        social:
          - url: https://med.uoi.gr/index.php?lang=el
            url_description: University of Ioannina website
            icon: fas fa-link
          # - url: https://facebook.com
          #   icon: fab fa-facebook-f
          # - url: https://linkedin.com
          #   icon: fab fa-linkedin-in
      - name: "DRAXIS ENVIRONMENTAL"
        role: "Company 1"
        image: assets/img/team/draxis.png
        social:
          - url: https://draxis.gr/
            url_description: DRAXIS ENVIRONMENTAL website
            icon: fas fa-link
          # - url: https://facebook.com
          #   icon: fab fa-facebook-f
          # - url: https://linkedin.com
          #   icon: fab fa-linkedin-in
      - name: "Tero"
        role: "Company 2"
        image: assets/img/team/tero.jpg
        social:
          - url: https://www.tero.gr/
            url_description: Tero website
            icon: fas fa-link
          # - url: https://facebook.com
          #   icon: fab fa-facebook-f
          # - url: https://linkedin.com
          #   icon: fab fa-linkedin-in
          
contact:
    title: "Contact Us"
    text: "Feel free to contact us for further infomartion"
    section: contact
    
footer:
    legal: "Privacy Policy"
    # social:
    #   - url: https://twitter.com
    #     icon: "fab fa-twitter"  
    #   - url: https://facebook.com
    #     icon: "fab fa-facebook-f"
    #   - url: https://linkedin.com
    #     icon: "fab fa-linkedin-in"
    #   - url: https://github.com/raviriley/agency-jekyll-theme
    #     icon: "fab fa-github"
    #   - url: https://instagram.com
    #     icon: "fab fa-instagram"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
